addSbtPlugin("com.typesafe.play"    % "sbt-plugin"                  % "2.7.4")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"                % "2.2.1")
addSbtPlugin("org.wartremover"      % "sbt-wartremover"             % "2.4.3")
addSbtPlugin("org.wartremover"      % "sbt-wartremover-contrib"     % "1.3.1")
addSbtPlugin("net.vonbuchholtz"     % "sbt-dependency-check"        % "1.3.3")
